version: '3.8'
services:
  n8n:
    image: 'n8nio/n8n:stable'
    restart: always
    environment:
      - 'N8N_EDITOR_BASE_URL=https://${SERVICE_FQDN_N8N}'
      - 'N8N_WEBHOOK_URL=https://${SERVICE_FQDN_N8N}'
      - 'N8N_ENCRYPTION_KEY=${SERVICE_PASSWORD_ENCRYPTION}'
      - 'N8N_BLOCK_ENV_ACCESS_IN_NODE=${N8N_BLOCK_ENV_ACCESS_IN_NODE:-true}'
      - 'GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/Chicago}'
      - 'TZ=${TZ:-America/Chicago}'
      - DB_TYPE=postgresdb
      - 'DB_POSTGRESDB_HOST=${POSTGRES_HOST}'
      - 'DB_POSTGRESDB_PORT=${POSTGRES_PORT:-5432}'
      - 'DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}'
      - 'DB_POSTGRESDB_USER=${POSTGRES_USER:-n8n}'
      - 'DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}'
      - EXECUTIONS_MODE=queue
      - 'QUEUE_BULL_REDIS_HOST=${REDIS_HOST}'
      - 'QUEUE_BULL_REDIS_PORT=${REDIS_PORT:-6379}'
      - 'QUEUE_BULL_REDIS_USERNAME=${REDIS_USER}'
      - 'QUEUE_BULL_REDIS_PASSWORD=${REDIS_PASSWORD}'
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

      # We REMOVE the broker/listener variables below because 
      # the WORKER is now the one listening.
      # - N8N_RUNNERS_MODE=external           <-- Removed
      # - N8N_RUNNERS_BROKER_LISTEN_ADDRESS   <-- Removed
      # - N8N_RUNNERS_BROKER_PORT             <-- Removed
      # - N8N_RUNNERS_AUTH_TOKEN              <-- Removed
    volumes:
      - 'n8n-data:/home/node/.n8n'
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget --spider --quiet http://127.0.0.1:5678/healthz || exit 1'
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 60s
volumes:
  n8n-data: null
